### ISSUE TITLE
Website does not document that IRC tags are in non-deterministic order

### ISSUE THREAD

**Issue by S0und** [robotty/recent-messages2#278]
The original message from twitch:
```
@badge-info=predictions/YES,subscriber/1;
badges=predictions/blue-1,subscriber/0,sub-gifter/10;
color=#FF0000;
display-name=NotoriousRobEG;
emotes=;
first-msg=0;
flags=;
id=32b02467-7424-47ae-9feb-c20ee9789f9d;
mod=0;
returning-chatter=0;
room-id=39763722;
subscriber=1;
tmi-sent-ts=1673747902193;
turbo=0;
user-id=192901116;
user-type= :notoriousrobeg!notoriousrobeg@notoriousrobeg.tmi.twitch.tv PRIVMSG #star0chris :Ain beat getting over it yesterday
```

Same line stored in RM2:

```
@mod=0;
color=#FF0000;
user-type=;
user-id=192901116;
first-msg=0;
badges=predictions/blue-1,subscriber/0,sub-gifter/10;
subscriber=1;
flags=;
emotes=;
tmi-sent-ts=1673747902193;
turbo=0;
room-id=39763722;
historical=1;
rm-received-ts=1673747902506;
badge-info=predictions/YES,
subscriber/1;
returning-chatter=0;
id=32b02467-7424-47ae-9feb-c20ee9789f9d;
display-name=NotoriousRobEG :notoriousrobeg!notoriousrobeg@notoriousrobeg.tmi.twitch.tv PRIVMSG #star0chris :Ain beat getting over it yesterday
```

Why everything is shuffled around? 

![image](https://user-images.githubusercontent.com/1266308/212518754-2a0e694a-06cf-4c62-b0b1-074348799e95.png)

vs

![image](https://user-images.githubusercontent.com/1266308/212519436-2781b6f1-d2ad-4f8e-8931-2b8298105c4b.png)

Every single line starts differently. Why?

**Comment by mkody** [comment]
The IRCTags are stored in a HashMap [(twitch-irc-rs code)](https://github.com/robotty/twitch-irc-rs/blob/master/src/message/tags.rs#L71) which are not returned in a specific order when iterating due to the hasher.  

You shouldn't expect to find everything in the same order (especially since the number of tags varies per message anyways) and should parse all key/values in your preferred array/map/dict type for future use.

**Comment by S0und** [comment]
I'm not sure what changed recently, but i'm using this api since 2022.02.27, and i didn't had to do why fiddling with it, all i had to do it just plug it into my chat message parser and worked. The reason it stopped working, because it's not following Twitch message structure anymore. 

The API example is clearly follows Twitch's message structure, so yes, **i should expect the same behavior**: https://recent-messages.robotty.de/api

```
Response format:

{
    "messages": [
        "@badge-info=;badges=glhf-pledge/1;color=;display-name=purplereddish;emotes=;flags=;historical=1;id=dbb10be8-581e-4f22-ba12-2001e088529d;mod=0;rm-received-ts=1596061057185;room-id=71092938;subscriber=0;tmi-sent-ts=1596061056790;turbo=0;user-id=260969632;user-type= :purplereddish!purplereddish@purplereddish.tmi.twitch.tv PRIVMSG #xqcow LULW",
        "@badge-info=subscriber/9;badges=subscriber/9;client-nonce=33d3d9d8e82c331dd877b6c5f4ed52ba;color=#FF0000;display-name=daraz1505;emotes=;flags=;historical=1;id=a36cddd8-06ba-4aed-b693-f503adb97010;mod=0;rm-received-ts=1596061057504;room-id=71092938;subscriber=1;tmi-sent-ts=1596061057059;turbo=0;user-id=171679991;user-type= :daraz1505!daraz1505@daraz1505.tmi.twitch.tv PRIVMSG #xqcow :monkaW ????????",
        "@badge-info=subscriber/1;badges=subscriber/0,glhf-pledge/1;color=#FF69B4;display-name=prospector07;emote-only=1;emotes=1035681:0-3,5-8,10-13;flags=;historical=1;id=559b9ccd-11b5-472c-83ce-e16a66fc7533;mod=0;rm-received-ts=1596061057607;room-id=71092938;subscriber=1;tmi-sent-ts=1596061057234;turbo=0;user-id=531980156;user-type= :prospector07!prospector07@prospector07.tmi.twitch.tv PRIVMSG #xqcow :xqcH xqcH xqcH",
        "@badge-info=subscriber/2;badges=subscriber/2,glhf-pledge/1;client-nonce=299f6ffc0dabe15f806cb4844a2fdebc;color=#9ACD32;display-name=siriwhatsmyname;emotes=;flags=;historical=1;id=fa0856e3-45d7-496e-97bd-93f941fd96ce;mod=0;rm-received-ts=1596061058007;room-id=71092938;subscriber=1;tmi-sent-ts=1596061057535;turbo=0;user-id=208278150;user-type= :siriwhatsmyname!siriwhatsmyname@siriwhatsmyname.tmi.twitch.tv PRIVMSG #xqcow :WEEBSOUT WEEBSOUT WEEBSOUT WEEBSOUT WEEBSOUT WEEBSOUT",
        "@badge-info=;badges=;client-nonce=b45518444921abc86bcca74e6f961c31;color=#FF0000;display-name=Scarrov;emotes=;flags=;historical=1;id=05836fc5-76e0-45de-b0be-779c223b160b;mod=0;rm-received-ts=1596061058008;room-id=71092938;subscriber=0;tmi-sent-ts=1596061057664;turbo=0;user-id=195960862;user-type= :scarrov!scarrov@scarrov.tmi.twitch.tv PRIVMSG #xqcow ????????",
        "@historical=1;rm-received-ts=1596061229295;room-id=71092938;slow=5 :tmi.twitch.tv ROOMSTATE #xqcow",
        "@historical=1;msg-id=slow_on;rm-received-ts=1596061229296 :tmi.twitch.tv NOTICE #xqcow :This room is now in slow mode. You may send messages every 5 seconds.",
        "@badge-info=subscriber/29;badges=subscriber/24;color=#7AC2A7;display-name=gw_ua;emotes=;flags=;historical=1;id=3391449d-3427-490f-836b-f5b8c1c98b93;mod=0;rm-deleted=1;rm-received-ts=1596059993412;room-id=71092938;subscriber=1;tmi-sent-ts=1596059993026;turbo=0;user-id=81302568;user-type= :gw_ua!gw_ua@gw_ua.tmi.twitch.tv PRIVMSG #xqcow :gn i guess",
        "@historical=1;login=gw_ua;rm-received-ts=1596061327989;room-id=;target-msg-id=3391449d-3427-490f-836b-f5b8c1c98b93;tmi-sent-ts=1596061327703 :tmi.twitch.tv CLEARMSG #xqcow :gn i guess",
    ],
    "error": null,
    "error_code": null
}
```

**Comment by RAnders00** [comment]
What @mkody has said is correct. The order of the tags is defined by the IRCv3 standard to be irrelevant. See here: https://ircv3.net/specs/extensions/message-tags

> The ordering of tags is not meaningful.

Because of this, you'll unfortunately have to solve this in your own code, since I'd consider this to be a bug on your own end - you were relying on undocumented behaviour. Twitch returns tags in alphabetical order, in the example above you can already see this not being the case anymore with @historical=1 being added to the front for example.

I do agree though that the example on the website should show the seemingly random order of the tags. I'll take that up as an issue.

**Comment by S0und** [comment]
All do respect, you have a weird fascination with IRCv3 and standards. From my perspective there is one standard when it comes to IRC and that one is provided by Twitch. Obviously i mean this in the context of Twitch. 
You might not remember but in the past we've exchanged a couple of emails. With the exact the same topic. You following the IRC standard, and me who tries to handle the only "standard" that i have to work with, which provided by Twitch. And yes if they deviate from the IRC standard, i have to support it. 

I do understand your point IRCv3, but the question is, who is this API for? I would assume this API will be used in some form of Twitch related application, and from my API-consuming-perspective it's not a crazy expectation to have the returned IRC tags in the same order as Twitch provides them. Although this behavior is not demanded by IRCv3, while doing so you can increase the API compatibility to 100%. For message parsers which worked "order independently" would not matter, but i'm pretty sure i'm not the only one who wrote the parser in a faction where IRC order tag matters. Because let's be real, at this point it's highly unlikely that Twitch ever gonna drop alphabetical order tags format. 

>  I'd consider this to be a bug on your own end 

This just the matter of perspective. From my point of view, the app i'm building parses _Twitch IRC messages_ perfectly, and it used to parse yours while the IRC tags were in an alphabetical order. 

I would like to have one more question. Would it be possible to add a parameter to the API, so when (for example) `?ordertags=1` provided, then the API would order the IRC tags in the same fashion as Twitch does? So you could store the messages the most efficient way on the back-end, but the API-consumer could have an option to have the returned messages in the exact same form as if Twitch provided them. Obviously with the additional `rm` related tags.

**Comment by mkody** [comment]
Nothing much to add [but just note from the Twitch docs](https://dev.twitch.tv/docs/irc/tags/#:~:text=The%20Twitch%20IRC,ignore%20the%20others.):

> The Twitch IRC server follows the [IRCv3 Message Tag specification](https://ircv3.net/specs/extensions/message-tags.html) for including tags in messages. Tags are optional metadata that Twitch attaches to an IRC message. Tags are key/value pairs (key=value). The key’s value is optional (key=). **Tags may appear in any order.** You should only parse tags you recognize and ignore the others.

_(Emphasis mine.)_
Sure they might not just drop doing alphabetical anytime soon but it's still not out of spec. _Still_, it should not be an issue with software and if it is, what if Twitch adds/drops/move a tag because they feel like it?

**Comment by S0und** [comment]
But this is exactly the beauty of Twitch, it doesn't matter what the doc says. What is the point mentioning "Tags may appear in any order." in the docs, then proceeding and ordering the tags anyway for years? What's the point of quoting the standard when  not  sticking to the said standard? In my book this is nothing more then cosmetic words.

**Comment by RAnders00** [comment]
I don't get why you're so angry with me. Are you asking me to sort the tags for you? I don't see the value that it adds, because a properly written message parser shouldn't care about the order of the tags, in fact, the order should even be disregarded. It would place additional unecessary load on my server with no added value, as far as I can see, and it would encourage relying on the order, which is, as we found out, incorrect.

Just fix your parser, please. Parsing IRC messages is not that hard, the format is designed to be easy to parse with operations such as string-splitting. Then just collect all the data into a hashmap. If you want, you can follow this: https://github.com/robotty/twitch-irc-rs/blob/master/src/message/mod.rs#L180 or just follow IRCv3 and RFC2812: https://www.rfc-editor.org/rfc/rfc2812#section-2.3.1

The reason why I'm "obsessed" with the standard is because it's an interface that's well-designed and has well-written rules that ensure all implementations of the standard can integrate seamlessly, given the implementations simply follow the standard. Trying to get your thing to work with all previously-existing M implementations becomes the much-simpler making your implementation follow the standard, and that allows everything to work together smoothly.

It's the same reason why JSON isn't sorted, neither does it matter whether it's prettyfied, or you could think of a million more examples where there's ambiguity in a data format that parsers must be resilient against, because there's no objective one right variant out of the ambiguous versions.

**Comment by RAnders00** [comment]
New website version is now live at https://recent-messages.robotty.de/api
